### ISSUE TITLE
"Refresh" button

### ISSUE THREAD

**Issue by versusbassz** [versusbassz/wp-meta-viewer#24]
TODO after #7 

## Subtasks
- [x] add "Refresh data" button to the top of the widget to the right of the "Search" functionality
- [x] something for AJAX requests: axios | native fetch ([caniuse](https://caniuse.com/?search=fetch)) --- let's start with native fetch (95% compatible)
- [x] Security: allow requests for REST API handler only for a user that "can_edit" requested item's data | capability "manage_options | delete_plugins ???" --- **chose `delete_users`, for now**
- [x] nonce
- [x] display smth if error happened
- [x] "Done!" message (color: green) on successful update, getting hidden after 1.5 sec.
- [x] display "Last update" even for an initial state
- [x] lock the button during request
- [x] phrase on the left: "Last updated: H:i:s am/pm"

## Docs
- https://wordpress.org/support/article/roles-and-capabilities/
- https://codex.wordpress.org/WordPress_Nonces
- https://developer.wordpress.org/themes/theme-security/using-nonces/

**Comment by versusbassz** [comment]
Seems done, not perfect, but mostly done.

**Comment by versusbassz** [comment]
Capabilities were changed in #39
