### ISSUE TITLE
Move to React

### ISSUE THREAD

**Issue by versusbassz** [versusbassz/wp-meta-viewer#7]
To do after #6 (upd: done)

## Subtasks
- [x] Use real data from DB
- [x] state management (React.Context ???) --- IMO, it isn't necessary for now, coz the widget is too small and independent + it doesn't have too much sub-components
- [x] search for react-libraries to replace the current jquery-like ones
    - `js-cookie` library stays installed via npm
    - `stupidtable` removed
- [x] wrapping layout for entities that don't support Metabox API 

## Notes
- https://reactjs.org/docs/create-a-new-react-app.html#creating-a-toolchain-from-scratch
- g: react trigger render from outside
	- https://stackoverflow.com/questions/31856712/update-component-state-from-outside-react-on-server-response
- https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event

**Comment by versusbassz** [comment]
I think, It's done.
